### PR TITLE
fix immutable hash-tables

### LINKED ISSUE #1: Converts immutable hashes into mutable ones
``` racket
#lang racket/base
(require mzlib/pconvert)
(print-convert (hash 1 2))
; '(make-hash (list (cons 1 2))), should be '(make-immutable-hash (list (cons 1 2)))
```

### PR DESCRIPTION
**Pull request by AlexKnauth**
fixes https://github.com/racket/pconvert-lib/issues/1

### CODE REVIEW

**Comment by AlexKnauth** [comment]
The functions `make-immutable-hash` and `make-immutable-hasheq` don't seem to be defined in mzscheme, although `make-immutable-hasheqv` is.

**Comment by samth** [comment]
I think the tests for this are here: https://github.com/racket/compatibility/blob/master/compatibility-test/tests/mzlib/pconvert.rktl

**Comment by rfindler** [comment]
Looks good to me.

**Comment by AlexKnauth** [comment]
Does that mean this should be merged?

**Comment by rfindler** [comment]
Thanks, I've pushed the commits. (I didn't try to put the code with it's test suite in the same library.)

**Pull request closed without merging**
