### PR TITLE
Use make-prefab-struct instead of constructor for prefab structs

### LINKED ISSUE #3: Prefab structs
Right now, this is what it does for prefab structs:

``` racket
#lang racket/base
(require mzlib/pconvert)
(print-convert '#s(base-measure-unit hello world))
; '(base-measure-unit 'hello 'world)
```

And this is causing bugs with adding measures to typed racket.
Would it be better to use either `quasiquote` or `make-prefab-struct`, so that prefab structs can be converted without requiring that `base-measure-unit` be bound to a constructor?

### PR DESCRIPTION
**Pull request by AlexKnauth**
closes #3

### CODE REVIEW

**Comment by samth** [comment]
I think there are tests for pconvert somewhere.

Also, you might use for/list and in-vector to avoid the intermediate list.

**Comment by AlexKnauth** [comment]
I just added a test.

**Comment by AlexKnauth** [comment]
For that I used the same pattern as https://github.com/racket/pconvert-lib/pull/4/files#diff-cb76abd3c1f365f0647a55475b35155eL475 a few lines later, but with a direct use of recur instead of a lambda.

**Comment by AlexKnauth** [comment]
What do you think?

**Comment by samth** [comment]
Looks reasonable to me. Avoiding the intermediate list would look like

```
(for/list ([i (in-vector (struct->vector expr)]
           [j (in-naturals)]
           #:unless (zero? j))
  (recur i))
```

**Comment by AlexKnauth** [comment]
Do you want me to change the https://github.com/racket/pconvert-lib/pull/4/files#diff-cb76abd3c1f365f0647a55475b35155eL475 a few lines later too? Come to think of it I could change https://github.com/racket/pconvert-lib/pull/4/files#diff-cb76abd3c1f365f0647a55475b35155eL163 to avoid intermediate lists as well. (Edit: and this https://github.com/racket/pconvert-lib/pull/4/files#diff-cb76abd3c1f365f0647a55475b35155eL160) (Further edit: and this https://github.com/racket/pconvert-lib/pull/4/files#diff-cb76abd3c1f365f0647a55475b35155eL281) (Further edit: and this https://github.com/racket/pconvert-lib/pull/4/files#diff-cb76abd3c1f365f0647a55475b35155eL394)

**Comment by samth** [comment]
Up to you. That could also be a separate change -- I think this is good to go as is.

**Comment by AlexKnauth** [comment]
I think it should be a separate change.

**Comment by AlexKnauth** [comment]
I'll make a separate pull request after.

**Comment by AlexKnauth** [comment]
Are you going to merge?

**Comment by samth** [comment]
Done.

**Comment by AlexKnauth** [comment]
Is `for` not provided by `mzscheme`?

**Comment by samth** [comment]
That wouldn't shock me. Porting the code to `racket/base` would also be nice ...

**Pull request closed without merging**
